### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by PoisonNinja**
I used Atom's style. This makes it much easier to read. I can convert all the tabs to spaces if needed, but IMHO tabs are much easier to work with.

Also, I may have broken something when formatting, so test this before merging.

### CODE REVIEW

**Comment by PoisonNinja** [comment]
Just tested it. It didn't break anything.

**Comment by PoisonNinja** [comment]
New commit also makes it load the menu and schedule on load. Information taken from https://developers.google.com/apps-script/guides/triggers/installable. The reason why it wouldn't load was because onOpen is a simple trigger, and simple triggers can't do actions that need authentication. However, installable triggers can. We work around this by creating a trigger in onOpen, which will call init() when the spreadsheet is opened. init() will then do whatever onOpen needs to do.

**Comment by PoisonNinja** [comment]
It didn't work

**Comment by PoisonNinja** [comment]
nvm it did. I'm really confused

**Comment by liavt** [comment]
I originally did the triggers, but when you copy the document, it doesn't copy triggers. Try it yourself. We need to find a way to do it without using Google's api.

**Comment by PoisonNinja** [comment]
This creates the triggers using code, not the UI. The first time you click on the Titan head, it will create the appropriate triggers. The next time you refresh, it persists. Since this is all code, it will work in the new copy.

**Comment by PoisonNinja** [comment]
Abandoning this. Going around for another try

**Comment by liavt** [comment]
What was the problem with what you had here?

**Comment by PoisonNinja** [comment]
The commit history is too messy. Random code that doesn't even match the commit message

**Pull request closed without merging**
