### PR TITLE
Multi grade level

### PR DESCRIPTION
**Pull request by liavt**

### CODE REVIEW

**Comment by PoisonNinja** [comment]
Please don't squash commits like this...

-1

**Comment by liavt** [comment]
I messed the master branch up. I accidently removed multi grade level support and need to re add it.

**Comment by PoisonNinja** [comment]
I know. You should reset the master branch. Can you disable force-push protection for a couple minutes.

**Comment by liavt** [comment]
ah ok

**Comment by PoisonNinja** [comment]
``` Shell
git fetch
git checkout temp
```

and cherry-pick the commits that you need.

**Comment by PoisonNinja** [comment]
What exactly was changed in 031ca2ead0a021d0e056caca233112cb4da04c3e?

**Comment by liavt** [comment]
I should have merged that into master instead of overwriting.

**Comment by PoisonNinja** [comment]
Can you disable force-push protection?

**Comment by liavt** [comment]
ok

**Comment by liavt** [comment]
Done

**Comment by PoisonNinja** [comment]
Can you take a look at the temp branch? I'm going to reset the master branch to the temp branch.

**Comment by liavt** [comment]
Also the live schedule should have the merged code by tomorrow. Mrs. Hirsch wants to use it tommorow

**Comment by PoisonNinja** [comment]
ok. I'll tidy up somethings before.

**Comment by PoisonNinja** [comment]
wtf i didn't merge it

**Comment by PoisonNinja** [comment]
The old code is in the backup branch, and you can reenable force-push protection if you want, @liavt.

**Pull request closed without merging**
