### PR TITLE
Remote test

### PR DESCRIPTION
**Pull request by liavt**
Instead of having the script bound to the spreadsheet, I am trying to figure out how to make it run code from Github. That way, they won't ever have to redownload the spreadsheet, under any circumstance. Before I make any new forced update, I want to make sure this works.

### CODE REVIEW

**Comment by liavt** [comment]
Currently it doesn't work. Try it out for yourself. I am trying different things to see if it works.

**Comment by PoisonNinja** [comment]
I don't think you can load external Javascript code. How about publishing the script as an add-on for sheets, and update the add-on when needed? https://developers.google.com/apps-script/add-ons/publish

**Comment by liavt** [comment]
Sheet add-ons don't have the ability to open UI stuff. I have tried this a long time ago, but SpreadsheetApp.getUi() only works on bound scripts.

**Comment by PoisonNinja** [comment]
This sucks. What if we automatically downloaded the new spreadsheet, and then deleted the old one? I know that's possible.

**Comment by liavt** [comment]
The only problem with that is you can't edit code on other spreadsheet. I did think of something though. We have a separate spreadsheet that has all the code in one cell. We just load that cell into HTML at runtime and run it's functions. I will work on that.

**Comment by liavt** [comment]
Got it. Google scripts has a library function. I just created a new library and shared it with the new schedule. This should theoretically work. Only problem now is that if you want to run a function from it in HTML, you have to do google.script.run.runRemote(functionname, args) I am changing the HTML to reflect this. I have shared the new library with you.

**Comment by PoisonNinja** [comment]
I see it. I'll take a closer look once I'm at school

**Comment by liavt** [comment]
It doesn't work completely. I will share you with the test spreadsheet. It's called "personal schedule." It has client.gs on it and has the schedule app shared with it. I have to depart for school, so I won't respond for like an hour.

**Comment by PoisonNinja** [comment]
I rebased this. You will need to run the following commands in order to continue on this branch:
git fetch
git checkout remote-test
git reset --hard origin/remote-test

**Comment by liavt** [comment]
Are you trying to merge with master? It's noot ready yet.

**Comment by PoisonNinja** [comment]
No, but you can merge it once it's ready. I fixed the merge conflicts

**Comment by PoisonNinja** [comment]
Make sure you ran the commands I listed above.

**Comment by liavt** [comment]
If you need command line use Cloud9

**Comment by PoisonNinja** [comment]
I use the terminal on Ubuntu

**Comment by liavt** [comment]
ah that also works

**Comment by PoisonNinja** [comment]
Do you know if added libraries persist across shared copies?

**Comment by PoisonNinja** [comment]
Everything besides the actual schedule is broken. It seems that personid doesn't seem to be loaded

**Comment by liavt** [comment]
Just fixed a lot of it. Only thing that doesn't work is clicking showcohort in the sidebar. trying to fix.

**Comment by PoisonNinja** [comment]
"personid" is not defined

**Comment by liavt** [comment]
Its fixed for me. I just tried with one of my groupmembers. When I update Schedule App, it doesn't update on their end, even directly on the document. Trying to figure out why it only updates for me...

**Comment by PoisonNinja** [comment]
I made a copy of your spreadsheet, and it's working again. I don't know why it worked.

**Comment by PoisonNinja** [comment]
The reason why the others don't work is because it's using a older version of the library.

**Comment by liavt** [comment]
But it's on development mode. Development mode just uses the newest version. You don't have to push a new version every time.

**Comment by liavt** [comment]
But otherwise, how would we tell the client to change their schedule? We don't want them to open script editor. Is it possible to override a past version with new code? Because there should be a way to update the library automatically

**Comment by PoisonNinja** [comment]
I need to test this more. However, when I edited the server.gs to pop up a box on init, it worked. Tell them to try again.

**Comment by PoisonNinja** [comment]
I know why it's not working. Quote from developer docs:
Testing and debugging your library

When you are using a debugger within a project that has a library included you are able to step into a function of the included library. The code shows up in the debugger in the read-only mode and at the right version.

When you are writing a library and doing a lot of testing, you should use Development Mode. Once the development mode is on, the following becomes true:

Anyone who has editor-level access to the script has the latest changes made to the files in the library project even if it was not saved as a version.
The autocomplete is still generated based on the selected version.
Anyone with only the read-level access to the script still uses the selected version regardless of whether the development mode is on or off.

Everyone else is using the library version that you selected, because they only have read access. To fix this, grant everyone write access, so then development mode will have an effect on them

**Comment by liavt** [comment]
But do we actually want everyone to have edit permission? That's a massive security risk.

**Comment by PoisonNinja** [comment]
I think most people don't know how to find it

**Comment by liavt** [comment]
Your right. It already is open source. Plus, to get the full link for it, it would be difficult.

**Comment by liavt** [comment]
Testing it with group members

**Comment by PoisonNinja** [comment]
I'll see if I can fix the cohort button

**Comment by liavt** [comment]
If someone does something malicious with it, we always have github. Just quickly copy and paste

**Comment by liavt** [comment]
I fixed the cohort button

**Comment by PoisonNinja** [comment]
Did you commit it?

**Comment by liavt** [comment]
No

**Comment by PoisonNinja** [comment]
I think it's ready to go

**Comment by liavt** [comment]
First test it with someone that isn't you

**Comment by PoisonNinja** [comment]
Ask Neel to test

**Comment by liavt** [comment]
asking him now

**Comment by NeelPi** [comment]
sure what do you want tested

**Comment by PoisonNinja** [comment]
The new spreadsheet

**Comment by NeelPi** [comment]
cohort doesn't work

**Comment by liavt** [comment]
showcohort doesnt work for him

**Comment by liavt** [comment]
o because it doesnt work
just a sec

**Comment by liavt** [comment]
It should work.

**Comment by liavt** [comment]
try to figure out why it doesnt work

**Comment by PoisonNinja** [comment]
Because you didn't update the code?

**Comment by liavt** [comment]
it should be fixed now

**Comment by liavt** [comment]
refreshing the page seems to help it
neel is testing now

**Comment by liavt** [comment]
it worked!

**Comment by liavt** [comment]
live update works

**Comment by liavt** [comment]
IT WORKS WITHOUT A REFERSH!

**Comment by liavt** [comment]
merging...

**Comment by liavt** [comment]
Updating live schedule. Gonna tell Bailey to force update soon

**Comment by NeelPi** [comment]
the update worked

**Comment by liavt** [comment]
like it should

**Comment by NeelPi** [comment]
when I updated my main schedule atomatically gave me my schedule without asking for my name

**Comment by liavt** [comment]
I have an idea. We keep on view only. When we want to update, we make it editable for like an hour, so everyone updates. That way, we keep security, and also live updates

**Comment by liavt** [comment]
We should also create a test document to test new stuff

**Comment by PoisonNinja** [comment]
I think that making it view only loads the selected library version. Even if you set everyone to edit and then back to view, then it will start loading the selected library instead of the latest.

**Comment by NeelPi** [comment]
update the version number

**Comment by liavt** [comment]
fixed the problem with the trigger. changed the trigger to updatespreadsheet instead of init. I don't want everyone to redownload everything again.

**Comment by PoisonNinja** [comment]
When copying the code from Github to the new spreadsheet, it broke the cohort thing. Fixed in b7f838a

**Comment by NeelPi** [comment]
unless you made an update the cohort feature is still working for me

**Comment by liavt** [comment]
Changed the trigger from updatespreadsheet to firstRun() so it still runs init(). It checks to make sure the triggers exist, and if they do, it doesn't prompt them anymore

**Comment by PoisonNinja** [comment]
I did do an update

**Comment by PoisonNinja** [comment]
We should stop commenting on this. Create a new issue if needed

**Pull request merged**
