### PR TITLE
Code cleanup and bug fixes

### PR DESCRIPTION
**Pull request by PoisonNinja**
Quick summary:
- Rearranged code into logical sections
- New file called Changelog.md that contains all the changes between versions (perhaps we can have a changelog button in About)
- Renamed Settings -> About
- Function to generate HTML code. No need to repeat the same code over and over when a function could have done it way easier
- Include 9:30 as part of school. Previously, school started at 9:31 according to the schedule, which is wrong.
- Formatting updates so it's easier to read

### CODE REVIEW

**Comment by PoisonNinja** [comment]
On a side note, why was Code.gs renamed to Code.js? You can't load .js files in Google Scripts

**Comment by PoisonNinja** [comment]
I forgot some changes:
- Rename onOpen -> firstRun, since that's the only time it actually gets run
- Confirm that this is the first time that you clicked it when you press on the button that says "Click Here on First Use"

**Comment by PoisonNinja** [comment]
Unified listAll function. No need to have 3 different functions that do essentially the same.

**Comment by PoisonNinja** [comment]
Rebased on latest upstream changes

**Comment by PoisonNinja** [comment]
@liavt can you give me write access? It's annoying to have to keep rebasing my changes.

**Comment by liavt** [comment]
Added as contributor. I also merged this into the main branch.

**Pull request closed without merging**
