### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by PoisonNinja**
Changes:
- Updated formatting so the loops don't look as scary as before
- Converted spaces to tabs (much easier to work with)
- Automagically create a trigger for init
- Automatically load the sidebar on page load

### CODE REVIEW

**Comment by PoisonNinja** [comment]
Do you think it would be better to keep the current system? I don't like refreshing the page every time.

**Comment by PoisonNinja** [comment]
I think we should have two buttons. One for first time setup, and one for refreshing the data without reloading the entire web page.

**Comment by liavt** [comment]
This would be better IMO. But I want this next update to be a bit bigger before I tell everyone to update (as I don't want to inconvenience them with this.) I'll probably tell them to update in like a week or two after everyone is comfortable with the new schedule

**Comment by PoisonNinja** [comment]
I can update my spreadsheet, and I'll submit the changes later.

**Comment by PoisonNinja** [comment]
The "Next" variable was undefined :) I fixed it now, so it properly reads "Next - End of school"

**Comment by PoisonNinja** [comment]
@liavt look at my spreadsheet for how I think it should work. https://docs.google.com/spreadsheets/d/1qQjMstaCPj4r-Q3V6APn4FfjZA_3zJ8-Lze48yyKrIY/edit#gid=0

**Comment by liavt** [comment]
Got it. I will merge this, but I will not send it to the actual program yet. Before pushing this update out, I want to make it run the code remotely, so that way you won't have to redownload the spreadsheet all the time.

**Pull request merged**
